# Change these first
owner: maxXx1 # Your GitHub organization or username, where this repository lives
repo: uptime-status # The name of this repository

sites:
  - name: Wildlee cloud (Brno)
    check: globalping
    target: wildlee.cloud
    locations:
      - city: Uherské Hradiště
        country: CZ
  - name: Hlubocky cloud (Hlubočky)
    check: globalping
    target: 176.97.241.251
    locations:
      - city: Uherské Hradiště
        country: CZ
  - name: Watchdog server (Kyjov)
    check: globalping
    target: 176.97.241.251
    locations:
      - city: Uherské Hradiště
        country: CZ
  - name: TeamSpeak3 server
    check: "tcp-ping"
    url: ts.maxxx.cz
    port: 10011
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.pokorak.cz
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Server uptime monitor
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: ¯\_(ツ)_/¯
  navbar:
    - title: Status
      href: /
    - title: Web
      href: https://pokorak.cz
    - title: Herní servery
      href: https://maxxx.cz
    - title: Github
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
