# Change these first
owner: maxXx1 # Your GitHub organization or username, where this repository lives
repo: uptime-status # The name of this repository

sites:
  - name: Wildlee cloud (Brno)
    icon: https://ftp.maxxx.cz/ico/cloud-server.png
    url: wildlee.cloud
    type: "globalping"
    check: "tcp-ping"
    location: "Brno+CZ"
    ipv6: false
  - name: Hlubocky cloud (Hlubočky)
    icon: https://ftp.maxxx.cz/ico/cloud-server.png
    url: hlubocky.online
    type: "globalping"
    check: "tcp-ping"
    location: "Brno+CZ"
    ipv6: false
  - name: TeamSpeak3 server
    icon: https://www.teamspeak.com/user/themes/teamspeak/images/favicon.ico
    check: "tcp-ping"
    url: ts.maxxx.cz
    port: 10011
  - name: Herní servery
    url: gg.maxxx.cz
    icon: https://maxxx.cz/storage/img/favico.png
    check: "tcp-ping"
    port: 80
  - name: f$ clan web
    url: http://fs.clanweb.eu
  - name: Xfire Fórum
    url: https://xfire.4fan.cz
  - name: Rohatorium festival
    url: https://www.rohatorium.4fan.cz
  - name: Terasy Kyjov
    url: https://terasykyjov.cz

    
status-website:
  themeUrl: https://status.pokorak.cz/discord.css
  robotsText: "User-agent: * \n Disallow: /"
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.pokorak.cz
  # baseUrl: /your-repo-name
  logoUrl: https://maxxx.cz/storage/img/logo.png
  name: Server uptime monitor
  introTitle: "Tento **watchdog** nezávisle monitoruje služby, které by měly běžet."
  introMessage: Pokud neběží, tak o tom nejspíš vím ¯\_(ツ)_/¯
  navbar:
    - title: Status
      href: /
    - title: Web
      href: https://pokorak.cz
    - title: Herní servery
      href: https://maxxx.cz
    - title: UptimeKuma
      href: https://uptime.maxxx.cz/status/srv

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  footer: Tahle stránka je [open source]($REPO), Vytvořil s 🍺 [Aleš](https://pokorak.cz)
