# Change these first
owner: maxXx1 # Your GitHub organization or username, where this repository lives
repo: uptime-status # The name of this repository

sites:
  - name: Wildlee cloud (Brno)
    icon: https://ftp.maxxx.cz/ico/cloud-server.png
    url: wildlee.cloud
    type: "globalping"
    check: "tcp-ping"
    location: "Brno+CZ"
    ipv6: false
  - name: Hlubocky cloud (Hlubočky)
    icon: https://ftp.maxxx.cz/ico/cloud-server.png
    url: hlubocky.online
    type: "globalping"
    check: "tcp-ping"
    location: "Brno+CZ"
    ipv6: false
  - name: TeamSpeak3 server
    icon: https://www.teamspeak.com/user/themes/teamspeak/images/favicon.ico
    check: "tcp-ping"
    url: ts.maxxx.cz
    port: 10011
  - name: Herní servery
    url: gg.maxxx.cz
    icon: https://maxxx.cz/storage/img/favico.png
    check: "tcp-ping"
    port: 80
  - name: f$ clan web
    icon: https://ftp.maxxx.cz/forsaken/fs_logo_150x150.png
    url: http://fs.clanweb.eu
  - name: Xfire Fórum
    icon: https://ftp.maxxx.cz/ico/xfire.png
    url: https://xfire.4fan.cz
  - name: Rohatorium festival
    icon: https://www.rohatorium.4fan.cz/wp-content/uploads/2018/02/cropped-detailmece-1.jpg
    url: https://www.rohatorium.4fan.cz
  - name: Terasy Kyjov
    url: https://terasykyjov.cz

    
status-website:
  themeUrl: https://status.pokorak.cz/discord.css
  robotsText: "User-agent: * \n Disallow: /"
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.pokorak.cz
  # baseUrl: /your-repo-name
  logoUrl: https://maxxx.cz/storage/img/logo.png
  name: Server uptime monitor
  introTitle: "Tento **watchdog** nezávisle monitoruje služby, které by měly běžet."
  introMessage: Pokud neběží, tak o tom nejspíš vím ¯\_(ツ)_/¯
  navbar:
    - title: Status
      href: /
    - title: Web
      href: https://pokorak.cz
    - title: Herní servery
      href: https://maxxx.cz
    - title: UptimeKuma
      href: https://uptime.maxxx.cz/status/srv

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  activeIncidents: Aktivní incidenty
  allSystemsOperational: Všechny systémy jsou v provozu
  incidentReport: "Zpráva o incidentu #$NUMBER →"
  activeIncidentSummary: "Otevřeno $DATE, počet příspěvků: $POSTS"
  incidentTitle: "Podrobnosti incidentu $NUMBER"
  incidentDetails: Detaily incidentu
  incidentFixed: Opraveno
  incidentOngoing: Probíhá
  incidentOpenedAt: Otevřeno
  incidentClosedAt: Uzavřeno
  incidentViewOnGitHub: Zobrazit a sledovat na GitHubu
  incidentCommentSummary: "Publikováno $DATE autorem $AUTHOR"
  incidentBack: "← Zpět na všechny incidenty"

  pastIncidents: Minulé incidenty
  pastIncidentsResolved: "Vyřešeno za $MINUTES minut, počet příspěvků: $POSTS"

  liveStatus: Aktuální stav
  overallUptime: "Celková dostupnost: $UPTIME"
  overallUptimeTitle: Celková dostupnost

  averageResponseTime: "Průměrná odezva: $TIME ms"
  averageResponseTimeTitle: Průměrná odezva
  sevelDayResponseTime: Odezva za posledních 7 dní
  responseTimeMs: Odezva (ms)

  up: V provozu
  down: Nedostupné
  degraded: Zhoršený stav
  ms: ms
  loading: Načítání…

  navGitHub: GitHub

  footer: "Tato stránka je [open‑source]($REPO), poháněná projektem [Upptime](https://upptime.js.org)"

  rateLimitExceededTitle: Překročen limit dotazů
  rateLimitExceededIntro: "Překročili jste počet povolených požadavků za hodinu. Počkejte prosím, nebo přidejte GitHub Personal Access Token pro pokračování."
  rateLimitExceededWhatDoesErrorMean: Co tato chyba znamená
  rateLimitExceededErrorMeaning: "Tato stránka používá GitHub API pro získání aktuálních dat o stavu služeb. GitHub povoluje každé IP adrese 60 požadavků za hodinu, což jste překročili."
  rateLimitExceededErrorHowCanFix: Jak to mohu opravit
  rateLimitExceededErrorFix: "Počkejte hodinu, než se limit obnoví, nebo přidejte GitHub Personal Access Token, který poskytuje dalších 5 000 požadavků za hodinu."
  rateLimitExceededGeneratePAT: Jak vytvořit Personal Access Token
  rateLimitExceededHasSet: Personal Access Token je nastaven.
  rateLimitExceededRemoveToken: Odebrat token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Vložte svůj token
  rateLimitExceededSaveToken: Uložit token

  errorTitle: Došlo k chybě
  errorIntro: "Při získávání aktuálního stavu došlo k chybě."
  errorText: "Zkuste to prosím znovu za okamžik."
  errorHome: Zpět na hlavní stránku

  pastScheduledMaintenance: Minulé plánované údržby
  scheduledMaintenance: Plánovaná údržba
  scheduledMaintenanceSummaryStarted: "Zahájeno $DATE, trvání $DURATION minut"
  scheduledMaintenanceSummaryStarts: "Začíná $DATE, plánované trvání $DURATION minut"
  startedAt: Zahájeno
  startsAt: Začíná
  duration: Trvání
  durationMin: "$DURATION minut"

  incidentCompleted: Dokončeno
  incidentScheduled: Naplánováno

  duration24H: 24 h
  duration7D: 7 dní
  duration30D: 30 dní
  duration1Y: 1 rok
  durationAll: vše

  locale: cs-CZ
