# Change these first
owner: maxXx1 # Your GitHub organization or username, where this repository lives
repo: uptime-status # The name of this repository

sites:
  - name: Herní servery
    url: gg.maxxx.cz
    check: "tcp-ping"
    port: 80
  - name: TeamSpeak3 server
    check: "tcp-ping"
    url: ts.maxxx.cz
    port: 10011
  - name: f$ clan web
    url: http://fs.clanweb.eu
  - name: Xfire Fórum
    url: https://xfire.4fan.cz
  - name: Rohatorium festival
    url: https://www.rohatorium.4fan.cz
  - name: Terasy Kyjov
    url: https://terasykyjov.cz
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.pokorak.cz
  # baseUrl: /your-repo-name
  logoUrl: https://maxxx.cz/storage/img/logo.png
  name: Server uptime monitor
  introTitle: "Tento **watchdog** nezávisle monitoruje služby, které by měly běžet."
  introMessage: ¯Pokud neběží, tak o tom nejspíš vím \_(ツ)_/¯
  navbar:
    - title: Status
      href: /
    - title: Web
      href: https://pokorak.cz
    - title: Herní servery
      href: https://maxxx.cz
    - title: Github
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 */6 * * *"
  responseTime: "10 */6 * * *"
  staticSite: "20 */6 * * *"
  summary: "30 */6 * * *"
  updateTemplate: "0 0 * * *"
  updates: "40 */6 * * *"
  uptime: "*/5 * * * *"
